<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('materials')->truncate();

        DB::table('materials')->insert([
            [
                'nama_material'     => 'Besi Beton 13mm',
                'kategori'          => 'Struktur',
                'harga'             => 185000,
                'deskripsi'         => 'Besi tulangan beton diameter 13mm untuk struktur bangunan ringan',
                'stok'              => 500,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Besi Beton 16mm',
                'kategori'          => 'Struktur',
                'harga'             => 220000,
                'deskripsi'         => 'Besi tulangan beton diameter 16mm untuk kolom dan balok',
                'stok'              => 400,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Besi Beton 19mm',
                'kategori'          => 'Struktur',
                'harga'             => 260000,
                'deskripsi'         => 'Besi tulangan beton diameter 19mm untuk struktur berat',
                'stok'              => 350,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Bata Ringan Walbric',
                'kategori'          => 'Dinding',
                'harga'             => 1500,
                'deskripsi'         => 'Bata ringan AAC merek Walbric, ringan dan hemat mortar',
                'stok'              => 2000,
                'satuan'            => 'pcs',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Bata Ringan JUMA',
                'kategori'          => 'Dinding',
                'harga'             => 1400,
                'deskripsi'         => 'Bata ringan AAC merek JUMA, kualitas premium',
                'stok'              => 2000,
                'satuan'            => 'pcs',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Batu Bata Merah',
                'kategori'          => 'Dinding',
                'harga'             => 900,
                'deskripsi'         => 'Batu bata merah bakar standar SNI untuk dinding',
                'stok'              => 5000,
                'satuan'            => 'pcs',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Atap Baja Ringan',
                'kategori'          => 'Atap',
                'harga'             => 95000,
                'deskripsi'         => 'Rangka atap baja ringan galvanis tahan karat',
                'stok'              => 300,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Kayu',
                'kategori'          => 'Struktur',
                'harga'             => 8000,
                'deskripsi'         => 'Kayu konstruksi serba guna untuk rangka dan bekisting',
                'stok'              => 800,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Pipa PVC Wavin 2 1/2',
                'kategori'          => 'Sanitasi',
                'harga'             => 75000,
                'deskripsi'         => 'Pipa PVC merek Wavin diameter 2.5 inci untuk saluran air',
                'stok'              => 200,
                'satuan'            => 'btg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Pipa PVC Wavin 3',
                'kategori'          => 'Sanitasi',
                'harga'             => 95000,
                'deskripsi'         => 'Pipa PVC merek Wavin diameter 3 inci untuk drainase',
                'stok'              => 200,
                'satuan'            => 'btg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Keramik Asia Tile',
                'kategori'          => 'Finishing',
                'harga'             => 85000,
                'deskripsi'         => 'Keramik lantai merek Asia Tile ukuran 40x40cm',
                'stok'              => 600,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Kaca',
                'kategori'          => 'Finishing',
                'harga'             => 120000,
                'deskripsi'         => 'Kaca bening 5mm untuk jendela dan pintu kaca',
                'stok'              => 150,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Cat Dinding Dulux',
                'kategori'          => 'Finishing',
                'harga'             => 180000,
                'deskripsi'         => 'Cat dinding interior-eksterior merek Dulux, pilihan warna lengkap',
                'stok'              => 300,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Cat Dinding Nobrand',
                'kategori'          => 'Finishing',
                'harga'             => 85000,
                'deskripsi'         => 'Cat dinding ekonomis berbagai warna',
                'stok'              => 400,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Pasir',
                'kategori'          => 'Material Dasar',
                'harga'             => 250000,
                'deskripsi'         => 'Pasir bangunan halus untuk adukan semen dan plester',
                'stok'              => 100,
                'satuan'            => 'm3',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Semen',
                'kategori'          => 'Material Dasar',
                'harga'             => 60000,
                'deskripsi'         => 'Semen Portland tipe I 40kg untuk konstruksi umum',
                'stok'              => 500,
                'satuan'            => 'sak',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Granite Tile',
                'kategori'          => 'Finishing',
                'harga'             => 250000,
                'deskripsi'         => 'Granit tile ukuran 60x60cm untuk lantai premium',
                'stok'              => 200,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Triplek Meranti Campur',
                'kategori'          => 'Struktur',
                'harga'             => 180000,
                'deskripsi'         => 'Triplek/plywood meranti campuran 9mm untuk bekisting dan partisi',
                'stok'              => 300,
                'satuan'            => 'lbr',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Besi WF 150',
                'kategori'          => 'Struktur',
                'harga'             => 2800000,
                'deskripsi'         => 'Besi Wide Flange 150x75mm untuk balok dan kolom baja',
                'stok'              => 100,
                'satuan'            => 'btg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Hollow Galvanis 4x4',
                'kategori'          => 'Struktur',
                'harga'             => 120000,
                'deskripsi'         => 'Hollow baja galvanis 4x4cm untuk rangka partisi dan plafon',
                'stok'              => 200,
                'satuan'            => 'btg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Semen Mortar MU-380',
                'kategori'          => 'Material Dasar',
                'harga'             => 75000,
                'deskripsi'         => 'Semen mortar siap pakai untuk pemasangan bata ringan',
                'stok'              => 400,
                'satuan'            => 'sak',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Batu Split',
                'kategori'          => 'Material Dasar',
                'harga'             => 350000,
                'deskripsi'         => 'Batu pecah/koral untuk pondasi dan campuran beton',
                'stok'              => 80,
                'satuan'            => 'm3',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Keramik 60x60 Polished',
                'kategori'          => 'Finishing',
                'harga'             => 180000,
                'deskripsi'         => 'Keramik homogeneous tile polished 60x60cm untuk ruang utama',
                'stok'              => 400,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Keramik Kamar Mandi',
                'kategori'          => 'Finishing',
                'harga'             => 95000,
                'deskripsi'         => 'Keramik dinding kamar mandi anti-slip 25x40cm',
                'stok'              => 350,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Plafon GRC',
                'kategori'          => 'Finishing',
                'harga'             => 55000,
                'deskripsi'         => 'Panel plafon GRC (Glassfiber Reinforced Cement) tahan air',
                'stok'              => 250,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Plafon Gypsum',
                'kategori'          => 'Finishing',
                'harga'             => 65000,
                'deskripsi'         => 'Plafon gypsum 9mm dengan rangka metal furing',
                'stok'              => 300,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Cat Eksterior Jotun',
                'kategori'          => 'Finishing',
                'harga'             => 220000,
                'deskripsi'         => 'Cat eksterior merek Jotun tahan cuaca dan jamur',
                'stok'              => 200,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Genteng Beton',
                'kategori'          => 'Atap',
                'harga'             => 8500,
                'deskripsi'         => 'Genteng beton standar untuk atap rumah tinggal',
                'stok'              => 1500,
                'satuan'            => 'pcs',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Genteng Metal',
                'kategori'          => 'Atap',
                'harga'             => 75000,
                'deskripsi'         => 'Genteng metal galvanis dengan lapisan anti karat',
                'stok'              => 200,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Pipa PPR 1/2 inci',
                'kategori'          => 'Sanitasi',
                'harga'             => 25000,
                'deskripsi'         => 'Pipa PPR untuk instalasi air bersih tahan suhu tinggi',
                'stok'              => 300,
                'satuan'            => 'btg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Stop Kran Kuningan',
                'kategori'          => 'Sanitasi',
                'harga'             => 85000,
                'deskripsi'         => 'Stop kran air dari bahan kuningan anti karat',
                'stok'              => 150,
                'satuan'            => 'pcs',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Kabel NYM 2x1.5',
                'kategori'          => 'Elektrikal',
                'harga'             => 6500,
                'deskripsi'         => 'Kabel listrik NYM 2x1.5mm untuk instalasi dalam ruangan',
                'stok'              => 1000,
                'satuan'            => 'm',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Kabel NYY 4x10',
                'kategori'          => 'Elektrikal',
                'harga'             => 45000,
                'deskripsi'         => 'Kabel daya NYY 4x10mm untuk panel utama',
                'stok'              => 300,
                'satuan'            => 'm',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Saklar + Stop Kontak Panasonic',
                'kategori'          => 'Elektrikal',
                'harga'             => 45000,
                'deskripsi'         => 'Set saklar tunggal dan stop kontak 2 lubang merek Panasonic',
                'stok'              => 200,
                'satuan'            => 'set',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Batu Alam Andesit',
                'kategori'          => 'Finishing',
                'harga'             => 350000,
                'deskripsi'         => 'Batu alam andesit untuk fasad eksterior dan dinding aksen',
                'stok'              => 100,
                'satuan'            => 'm2',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Multipleks 18mm',
                'kategori'          => 'Struktur',
                'harga'             => 350000,
                'deskripsi'         => 'Multiplex/kayu lapis 18mm untuk furniture built-in dan bekisting',
                'stok'              => 150,
                'satuan'            => 'lbr',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Aluminium Kusen',
                'kategori'          => 'Kusen & Pintu',
                'harga'             => 180000,
                'deskripsi'         => 'Kusen aluminium 4 inci untuk pintu dan jendela',
                'stok'              => 200,
                'satuan'            => 'm',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Pintu Kayu Solid',
                'kategori'          => 'Kusen & Pintu',
                'harga'             => 2500000,
                'deskripsi'         => 'Pintu panel kayu solid meranti ukuran 80x210cm',
                'stok'              => 50,
                'satuan'            => 'pcs',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Waterproofing Coating',
                'kategori'          => 'Struktur',
                'harga'             => 95000,
                'deskripsi'         => 'Coating waterproofing berbasis semen untuk dak beton dan kamar mandi',
                'stok'              => 200,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'nama_material'     => 'Kawat Bendrat',
                'kategori'          => 'Struktur',
                'harga'             => 25000,
                'deskripsi'         => 'Kawat ikat/bendrat untuk mengikat besi tulangan beton',
                'stok'              => 500,
                'satuan'            => 'kg',
                'path_foto_material'=> null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ]
        ]);
    }
}
