<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('materials')->insert([
            [
                'nama_material' => 'Besi Beton 19mm',
                'kategori' => 'Beton',
                'harga' => 320000,
                'satuan' => 'btg',
                'stok' => 2500,
                'deskripsi' => 'Perwira • 19mm • 27kg',
                'path_foto_material' => 'images/material/beton.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Bata Ringan Walbric',
                'kategori' => 'Hebel',
                'harga' => 740000,
                'satuan' => 'kubik',
                'stok' => 5000,
                'deskripsi' => 'Walbric • 60x20x10cm • 83pcs',
                'path_foto_material' => 'images/material/hebel.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Besi Beton 16mm',
                'kategori' => 'Beton',
                'harga' => 230000,
                'satuan' => 'btg',
                'stok' => 3000,
                'deskripsi' => 'AS Asia Steel • 16mm • 19kg',
                'path_foto_material' => 'images/material/beton.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Keramik Asia Tile',
                'kategori' => 'Keramik',
                'harga' => 60000,
                'satuan' => 'dus',
                'stok' => 9000,
                'deskripsi' => 'Asia Tile • 40x40cm • 17kg',
                'path_foto_material' => 'images/material/keramik.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Cat Dinding Dulux',
                'kategori' => 'Cat',
                'harga' => 915000,
                'satuan' => 'pail',
                'stok' => 10000,
                'deskripsi' => 'Dulux • Chrysan White • 25kg',
                'path_foto_material' => 'images/material/dulux.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Granite Tile',
                'kategori' => 'Granite',
                'harga' => 120000,
                'satuan' => 'dus',
                'stok' => 0,
                'deskripsi' => 'Niro • 60x60cm • 34kg',
                'path_foto_material' => 'images/material/granite.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Cat Dinding Nobrand',
                'kategori' => 'Cat',
                'harga' => 230000,
                'satuan' => 'pail',
                'stok' => 0,
                'deskripsi' => 'Nobrand • Acrylic Emulsion • 20kg',
                'path_foto_material' => 'images/material/nobrand.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Bata Ringan JUMA',
                'kategori' => 'Hebel',
                'harga' => 500000,
                'satuan' => 'kubik',
                'stok' => 8000,
                'deskripsi' => 'JUMA • 60x20x10cm • 83pcs',
                'path_foto_material' => 'images/material/hebel.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Triplek Meranti Campur',
                'kategori' => 'Triplek',
                'harga' => 175000,
                'satuan' => 'lembar',
                'stok' => 4000,
                'deskripsi' => 'Meranti Campur • 122cm x 244cm x 1.8cm • 20kg',
                'path_foto_material' => 'images/material/triplek.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pipa PVC Wavin 3\'',
                'kategori' => 'PVC',
                'harga' => 97000,
                'satuan' => 'btg',
                'stok' => 0,
                'deskripsi' => 'Wavin • 4m • Tipe D',
                'path_foto_material' => 'images/material/pvc.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Besi Beton 13mm',
                'kategori' => 'Beton',
                'harga' => 150000,
                'satuan' => 'btg',
                'stok' => 2000,
                'deskripsi' => 'AS Asia Steel • 13mm • 13kg',
                'path_foto_material' => 'images/material/beton.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pipa PVC Wavin 2 1/2\'',
                'kategori' => 'PVC',
                'harga' => 75000,
                'satuan' => 'btg',
                'stok' => 1000,
                'deskripsi' => 'Wavin • 4m • Tipe D',
                'path_foto_material' => 'images/material/pvc.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Kayu',
                'kategori' => 'Kayu',
                'harga' => 85000,
                'satuan' => 'meter',
                'stok' => 5000,
                'deskripsi' => 'Kayu solid 4x6cm • Kualitas standar',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/kayu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Atap Baja Ringan',
                'kategori' => 'Baja',
                'harga' => 45000,
                'satuan' => 'meter',
                'stok' => 3000,
                'deskripsi' => 'Baja ringan • Tebal 0.3mm • Panjang 6m',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/baja.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Semen',
                'kategori' => 'Semen',
                'harga' => 58000,
                'satuan' => 'sak',
                'stok' => 10000,
                'deskripsi' => 'Semen Portland • 50kg per sak',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/semen.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pasir',
                'kategori' => 'Pasir',
                'harga' => 120000,
                'satuan' => 'm3',
                'stok' => 2000,
                'deskripsi' => 'Pasir putih • Kualitas konstruksi',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pasir.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Batu Bata Merah',
                'kategori' => 'Batu',
                'harga' => 1200,
                'satuan' => 'buah',
                'stok' => 50000,
                'deskripsi' => 'Batu bata merah • 24x12x6cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/batubata.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Kaca',
                'kategori' => 'Kaca',
                'harga' => 65000,
                'satuan' => 'meter',
                'stok' => 2500,
                'deskripsi' => 'Kaca bening • Tebal 5mm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/kaca.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Batu Kapur',
                'kategori' => 'Batu',
                'harga' => 35000,
                'satuan' => 'sak',
                'stok' => 8000,
                'deskripsi' => 'Batu kapur • 50kg per sak',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/batu_kapur.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Paku Besi',
                'kategori' => 'Hardware',
                'harga' => 15000,
                'satuan' => 'kg',
                'stok' => 5000,
                'deskripsi' => 'Paku besi • Berbagai ukuran',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/paku.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Skrup Kayu',
                'kategori' => 'Hardware',
                'harga' => 25000,
                'satuan' => 'kg',
                'stok' => 3000,
                'deskripsi' => 'Skrup kayu • 3-5 inch',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/skrup.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Kawat Las',
                'kategori' => 'Baja',
                'harga' => 180000,
                'satuan' => 'kg',
                'stok' => 1000,
                'deskripsi' => 'Kawat las • Diameter 2.6mm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/kawat_las.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Plafon Gypsum',
                'kategori' => 'Plafon',
                'harga' => 45000,
                'satuan' => 'lembar',
                'stok' => 2000,
                'deskripsi' => 'Plafon gypsum • 120x120cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/plafon.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Genteng Keramik',
                'kategori' => 'Genteng',
                'harga' => 8000,
                'satuan' => 'buah',
                'stok' => 15000,
                'deskripsi' => 'Genteng keramik • Press',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/genteng.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Genteng Beton',
                'kategori' => 'Genteng',
                'harga' => 5000,
                'satuan' => 'buah',
                'stok' => 20000,
                'deskripsi' => 'Genteng beton • Flat type',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/genteng_beton.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Kayu Lapis',
                'kategori' => 'Kayu',
                'harga' => 95000,
                'satuan' => 'lembar',
                'stok' => 3000,
                'deskripsi' => 'Kayu lapis • 122x244cm • 9mm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/kayu_lapis.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pipa Besi Galvanis 1/2"',
                'kategori' => 'Pipa',
                'harga' => 45000,
                'satuan' => 'meter',
                'stok' => 4000,
                'deskripsi' => 'Pipa besi galvanis • 1/2 inch',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pipa_besi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pipa Besi Galvanis 3/4"',
                'kategori' => 'Pipa',
                'harga' => 65000,
                'satuan' => 'meter',
                'stok' => 3500,
                'deskripsi' => 'Pipa besi galvanis • 3/4 inch',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pipa_besi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pipa PVC Wavin 1"',
                'kategori' => 'PVC',
                'harga' => 120000,
                'satuan' => 'btg',
                'stok' => 2000,
                'deskripsi' => 'Wavin • 1 inch • 4m',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pvc.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Semen Warna Putih',
                'kategori' => 'Semen',
                'harga' => 85000,
                'satuan' => 'sak',
                'stok' => 3000,
                'deskripsi' => 'Semen putih • 50kg per sak',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/semen_putih.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pasir Kasar',
                'kategori' => 'Pasir',
                'harga' => 95000,
                'satuan' => 'm3',
                'stok' => 2500,
                'deskripsi' => 'Pasir kasar • Untuk konstruksi',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pasir_kasar.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Batu Split',
                'kategori' => 'Batu',
                'harga' => 105000,
                'satuan' => 'm3',
                'stok' => 2000,
                'deskripsi' => 'Batu split • Ukuran 2-3cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/batu_split.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Cat Kayu Mowilex',
                'kategori' => 'Cat',
                'harga' => 175000,
                'satuan' => 'liter',
                'stok' => 5000,
                'deskripsi' => 'Mowilex • Untuk kayu • 1 liter',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/cat_kayu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Cat Tembok Nippon',
                'kategori' => 'Cat',
                'harga' => 285000,
                'satuan' => 'liter',
                'stok' => 4000,
                'deskripsi' => 'Nippon • 1 liter',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/cat_tembok.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Dinding Panel',
                'kategori' => 'Panel',
                'harga' => 125000,
                'satuan' => 'lembar',
                'stok' => 1500,
                'deskripsi' => 'Panel dinding • 240x60cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/panel.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Flooring Vinyl',
                'kategori' => 'Flooring',
                'harga' => 95000,
                'satuan' => 'meter',
                'stok' => 2000,
                'deskripsi' => 'Vinyl flooring • 1 meter x 2 meter',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/vinyl.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Parket Kayu',
                'kategori' => 'Flooring',
                'harga' => 385000,
                'satuan' => 'meter',
                'stok' => 1000,
                'deskripsi' => 'Parket kayu jati • Premium',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/parket.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Keramik Lantai Motif',
                'kategori' => 'Keramik',
                'harga' => 85000,
                'satuan' => 'dus',
                'stok' => 6000,
                'deskripsi' => 'Keramik lantai • 60x60cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/keramik_motif.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Keramik Dinding',
                'kategori' => 'Keramik',
                'harga' => 45000,
                'satuan' => 'dus',
                'stok' => 8000,
                'deskripsi' => 'Keramik dinding • 30x60cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/keramik_dinding.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Marmer Tile',
                'kategori' => 'Marmer',
                'harga' => 425000,
                'satuan' => 'dus',
                'stok' => 500,
                'deskripsi' => 'Marmer tile • 60x60cm • Premium',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/marmer.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Besi Hollow 4x4',
                'kategori' => 'Baja',
                'harga' => 215000,
                'satuan' => 'meter',
                'stok' => 1000,
                'deskripsi' => 'Besi hollow • 4x4cm • 2mm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/hollow.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Besi Hollow 5x5',
                'kategori' => 'Baja',
                'harga' => 295000,
                'satuan' => 'meter',
                'stok' => 800,
                'deskripsi' => 'Besi hollow • 5x5cm • 2mm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/hollow.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pintu Kayu Jati',
                'kategori' => 'Pintu',
                'harga' => 1200000,
                'satuan' => 'unit',
                'stok' => 100,
                'deskripsi' => 'Pintu kayu jati • 80x210cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pintu_kayu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Pintu Aluminium',
                'kategori' => 'Pintu',
                'harga' => 750000,
                'satuan' => 'unit',
                'stok' => 200,
                'deskripsi' => 'Pintu aluminium • 80x210cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/pintu_alu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Jendela Aluminium',
                'kategori' => 'Jendela',
                'harga' => 385000,
                'satuan' => 'unit',
                'stok' => 300,
                'deskripsi' => 'Jendela aluminium • 100x120cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/jendela_alu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Jendela UPVC',
                'kategori' => 'Jendela',
                'harga' => 525000,
                'satuan' => 'unit',
                'stok' => 250,
                'deskripsi' => 'Jendela UPVC • 100x120cm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/jendela_upvc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Cat Anti Rayap',
                'kategori' => 'Cat',
                'harga' => 165000,
                'satuan' => 'liter',
                'stok' => 2000,
                'deskripsi' => 'Cat anti rayap • 1 liter',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/cat_rayap.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Primer Dinding',
                'kategori' => 'Cat',
                'harga' => 85000,
                'satuan' => 'liter',
                'stok' => 3500,
                'deskripsi' => 'Primer dinding • 1 liter',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/primer.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Acian Dinding',
                'kategori' => 'Cat',
                'harga' => 45000,
                'satuan' => 'kg',
                'stok' => 5000,
                'deskripsi' => 'Acian dinding • Putih • 1kg',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/acian.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Keran Air Kuningan',
                'kategori' => 'Plumbing',
                'harga' => 85000,
                'satuan' => 'unit',
                'stok' => 1000,
                'deskripsi' => 'Keran air • Kuningan standar',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/keran.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Lampu LED Downlight',
                'kategori' => 'Listrik',
                'harga' => 125000,
                'satuan' => 'unit',
                'stok' => 2000,
                'deskripsi' => 'Lampu LED • 12W • Downlight',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/lampu_led.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Instalasi Kabel NYM',
                'kategori' => 'Listrik',
                'harga' => 35000,
                'satuan' => 'meter',
                'stok' => 5000,
                'deskripsi' => 'Kabel NYM • 2x2.5mm',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/kabel.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_material' => 'Papan Nama',
                'kategori' => 'Dekorasi',
                'harga' => 250000,
                'satuan' => 'unit',
                'stok' => 300,
                'deskripsi' => 'Papan nama • Stainless • Custom',
                'path_foto_material' => 'https://ovyjfudrdwrlyioygotq.supabase.co/storage/v1/object/public/public-assets/materials/papan_nama.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}